### ISSUE TITLE
input redirection does not work

### ISSUE THREAD

**Issue by LatteWiiU** [Fangal-Airbag/Better-Settings#2]
I've tried a pro controller and classic controller pro, the input redirection is even enabled in the plugin settings, using a European Wii U if you need to know

**Comment by Fangal-Airbag** [comment]
Is the Gamepad on and connected to the Wii U?

**Comment by LatteWiiU** [comment]
No because

**Comment by LatteWiiU** [comment]
Accidentally closed this because phone moment, my gamepads are broken so no

**Comment by Fangal-Airbag** [comment]
Yeah so at the moment as stated in the README a gamepad must be connected for the input redirection to work. Hopefully support for this to not be the case will be added soon™️.
