### ISSUE TITLE
Could you please port this plugin for miimaker and other system applications as well?

### ISSUE THREAD

**Issue by uitojhb25153** [Fangal-Airbag/Better-Settings#3]
Could you please port this plugin for miimaker and other system applications as well?

**Comment by Neverends4** [comment]
Second this, if realized then the DRC will be not needed in most use cases, except certain games.

**Comment by Fangal-Airbag** [comment]
Hey there!

So I noticed you and some others have already forked this repository to add in these features yourselves and that's awesome! I personally was going to suggest the same thing. If someone is interested in forking Better-Settings and making a Better-WiiU I'd love that, although that is a bit out of scope for me. If anyone does have any questions about the codebase and would like to make their own versions I'm totally willing to help!

**Comment by uitojhb25153** [comment]
This source code cannot be built with the latest versions of wut and wups

**Comment by Fangal-Airbag** [comment]
Hey there! I’m planning an update very soon to resolve this. Keep on the lookout!
