### ISSUE TITLE
Add support for wii remote and nunchuck

### ISSUE THREAD

**Issue by Odyssey255** [Fangal-Airbag/Better-Settings#4]
The nunchuck Thumbstick and buttons for the Wii remote does not work properly in the system settings

**Comment by Fangal-Airbag** [comment]
Hi there!

Not sure if you noticed but in the Read Me I mentioned how there is only support for the Wii U Pro Controller and Wii Classic Controller. I personally have no intention of adding support for more controllers, however if you or anyone else made a pull request I'd gladly merge it!

**Comment by DolphinOfficial** [comment]
Hey there. I don’t know how to code, but it would be really nice to get Wii Remote support. After all, the goal of this plugin is to make using the Settings viable without the Gamepad! The Wii Remote is the only essential controller left you need to support, then it’d be a perfect plugin! What if you don’t have a Pro Controller?! C’mon, man!
